server:
  port: 8099
spring:
  application:
    name: task-service-api
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/task-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master_changelog.yaml
    enabled: true
